version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::567174634614:user/aws-sam-cli-managed-dev-env-pipeline-PipelineUser-1GF2NHC6B3YVJ"
permissions_provider = "AWS IAM"

[dev_env]
[dev_env.pipeline_bootstrap]
[dev_env.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::567174634614:role/aws-sam-cli-managed-dev-env-PipelineExecutionRole-MIU4GUTMMRLK"
cloudformation_execution_role = "arn:aws:iam::567174634614:role/aws-sam-cli-managed-dev-e-CloudFormationExecutionR-19VUGOXXDNCBO"
artifacts_bucket = "aws-sam-cli-managed-dev-env-pipel-artifactsbucket-1foknk6ov3yfm"
image_repository = ""
region = "us-east-1"

[prod_env]
[prod_env.pipeline_bootstrap]
[prod_env.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::567174634614:role/aws-sam-cli-managed-prod-env-PipelineExecutionRole-1V0HL70OOMVT3"
cloudformation_execution_role = "arn:aws:iam::567174634614:role/aws-sam-cli-managed-prod-CloudFormationExecutionR-EQPIDBB74536"
artifacts_bucket = "aws-sam-cli-managed-prod-env-pipe-artifactsbucket-k85hyb9xtewe"
image_repository = ""
region = "us-east-1"
